import { Header } from "@/components/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  RQ_CONFIG_ENDPOINT,
  RQ_CONFIG_KEY,
  RQ_LANGUAGES_ENDPOINT,
  RQ_LANGUAGES_KEY,
} from "@/constants";
import MyAPIClient from "@/services/myApiClient";
import { TMDB_API_Configuration } from "@/types/TMDB_API_Configuration";
import {
  HydrationBoundary,
  QueryClient,
  dehydrate,
} from "@tanstack/react-query";
import { ReactNode } from "react";
import "../globals.css";
import ReactQueryProvider from "./ReactQueryProvider";
import { Language } from "@/types/movies/Language";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

export default async function RootLayout({ children }: Props) {
  const queryClient = new QueryClient();

  // Config
  const apiClientConfig = new MyAPIClient<TMDB_API_Configuration>(
    RQ_CONFIG_ENDPOINT,
  );

  await queryClient.prefetchQuery({
    queryKey: [RQ_CONFIG_KEY],
    queryFn: () => apiClientConfig.getAll(),
  });

  // Languages
  const apiClientLanguages = new MyAPIClient<Language[]>(RQ_LANGUAGES_ENDPOINT);
  await queryClient.prefetchQuery({
    queryKey: [RQ_LANGUAGES_KEY],
    queryFn: () => apiClientLanguages.getAll(),
  });

  return (
    <html lang="en">
      <body className={inter.className} data-theme="dim">
        <ReactQueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Header />
            <main>{children}</main>
          </HydrationBoundary>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
